# Generated by Django 3.2.9 on 2021-12-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
